// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26tyN0d9WvU32_G1CSZlxMMdvc1IWhDY',
    appId: '1:130226500796:web:18f4f9d04da3aa3feb0cb9',
    messagingSenderId: '130226500796',
    projectId: 'attendance-checker-87ebd',
    authDomain: 'attendance-checker-87ebd.firebaseapp.com',
    storageBucket: 'attendance-checker-87ebd.firebasestorage.app',
    measurementId: 'G-4K7XXC2GMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq9r4RZV3MuCgLiwwpmWsaeAekE8yOrpw',
    appId: '1:130226500796:android:5f3c3d1c6e502945eb0cb9',
    messagingSenderId: '130226500796',
    projectId: 'attendance-checker-87ebd',
    storageBucket: 'attendance-checker-87ebd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbdGppTt7B5YsEUdUIXqYvd-6zDmZBGoE',
    appId: '1:130226500796:ios:03de74f1b50237b0eb0cb9',
    messagingSenderId: '130226500796',
    projectId: 'attendance-checker-87ebd',
    storageBucket: 'attendance-checker-87ebd.firebasestorage.app',
    iosBundleId: 'com.example.simpleattendancechecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbdGppTt7B5YsEUdUIXqYvd-6zDmZBGoE',
    appId: '1:130226500796:ios:03de74f1b50237b0eb0cb9',
    messagingSenderId: '130226500796',
    projectId: 'attendance-checker-87ebd',
    storageBucket: 'attendance-checker-87ebd.firebasestorage.app',
    iosBundleId: 'com.example.simpleattendancechecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB26tyN0d9WvU32_G1CSZlxMMdvc1IWhDY',
    appId: '1:130226500796:web:ac44cced73875e87eb0cb9',
    messagingSenderId: '130226500796',
    projectId: 'attendance-checker-87ebd',
    authDomain: 'attendance-checker-87ebd.firebaseapp.com',
    storageBucket: 'attendance-checker-87ebd.firebasestorage.app',
    measurementId: 'G-WPXMFZ07GD',
  );
}
