// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYD4wN8hgJ9VOTkBaLz_SABIkktp93TSM',
    appId: '1:640541823690:web:7fbb6a4f0f5df0be389a33',
    messagingSenderId: '640541823690',
    projectId: 'attendance-checker-47d12',
    authDomain: 'attendance-checker-47d12.firebaseapp.com',
    storageBucket: 'attendance-checker-47d12.firebasestorage.app',
    measurementId: 'G-F24BPZ32D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYnFdN6BBUBohgOLvHlj7PugL6aR3VotE',
    appId: '1:640541823690:android:1c9c4fd053a4adbb389a33',
    messagingSenderId: '640541823690',
    projectId: 'attendance-checker-47d12',
    storageBucket: 'attendance-checker-47d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsD9xRLQCM69uID9E1JtzowhEOXy8SwQ',
    appId: '1:640541823690:ios:8316ac43cd3ff346389a33',
    messagingSenderId: '640541823690',
    projectId: 'attendance-checker-47d12',
    storageBucket: 'attendance-checker-47d12.firebasestorage.app',
    iosBundleId: 'com.example.simpleattendancechecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsD9xRLQCM69uID9E1JtzowhEOXy8SwQ',
    appId: '1:640541823690:ios:8316ac43cd3ff346389a33',
    messagingSenderId: '640541823690',
    projectId: 'attendance-checker-47d12',
    storageBucket: 'attendance-checker-47d12.firebasestorage.app',
    iosBundleId: 'com.example.simpleattendancechecker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYD4wN8hgJ9VOTkBaLz_SABIkktp93TSM',
    appId: '1:640541823690:web:46c45ae03fa465bc389a33',
    messagingSenderId: '640541823690',
    projectId: 'attendance-checker-47d12',
    authDomain: 'attendance-checker-47d12.firebaseapp.com',
    storageBucket: 'attendance-checker-47d12.firebasestorage.app',
    measurementId: 'G-PFFFFER2Z2',
  );
}
